services:
  news-storage:
    image: application
    build:
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - db

  db:
    image: mysql:8.3.0
    environment:
      MYSQL_USER: sharphurt
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: news
    command: --init-file /data/application/init.sql
    ports:
      - "33061:3306"
    volumes:
      - ./src/main/resources/db/init.sql:/data/application/init.sql
      - ./dbdata:/var/lib/mysql
      - ./conf-mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    restart: unless-stopped

  rss-reader:
    image: rss-reader-app
    build: https://github.com/sharphurt/cron-rss-reader.git
    ports:
      - "8282:8282"
    depends_on:
      - news-storage

volumes:
  db-data: