CREATE DATABASE IF NOT EXISTS news;
USE news;

CREATE USER IF NOT EXISTS 'sharphurt'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON news.* TO 'sharphurt'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;